rules:
  - name: bucket_not_configured_block_public_access
    query: |
      SELECT
        *
      FROM
        aws_s3_accounts
      WHERE
        restrict_public_buckets = FALSE;
    labels:
      tags:
        - Attack Surface
        - Security
        - Misconfigure
        - CIS Benchmark
        - PCI
        - HIPAA
        - GDPR
        - ISO 27001
        - SOC 2
      standard:
        - CIS
        - PCI
        - HIPAA
        - GDPR
        - ISO 27001
        - SOC 2
      author: Selefra
    metadata:
      id: SF010113
      severity: High
      provider: AWS
      resource_type: S3
      resource_account_id: '{{.account_id}}'
      resource_id: '{{.account_id}}'
      resource_region: 'All Regions'
      remediation: remediation/s3/bucket_not_configured_block_public_access.md
      title: S3 Bucket not configured Block public access
      description: Ensure that S3 Buckets are configured with 'Block public access (bucket settings)' .
    output: 'S3 Bucket not configured Block public access, account id: {{.account_id}}'
