rules:
  - name: bucket_not_configured_block_public_access
    query: |
      SELECT
        *
      FROM
        aws_s3_accounts
      WHERE
        restrict_public_buckets = FALSE;
    labels:
      resource_account_id: '{{.account_id}}'
      resource_id: '{{.account_id}}'
      resource_region: 'All Regions'
      resource_type: S3
    metadata:
      author: Selefra
      description: Ensure that S3 Buckets are configured with 'Block public access (bucket settings)' .
      id: SF010113
      provider: AWS
      remediation: remediation/s3/bucket_not_configured_block_public_access.md
      severity: High
      tags:
        - Attack Surface
        - Security
        - Misconfiguration
        - CIS Benchmark
        - PCI
        - HIPAA
        - GDPR
        - ISO 27001
        - SOC 2
        - AWS Config
      title: S3 Bucket not configured Block public access
    output: "S3 Bucket not configured Block public access, account id: {{.account_id}}"
