rules:
  - name: bucket_is_not_configured_with_cors_rules
    query: |
      SELECT
        *
      FROM
        aws_s3_buckets AS a1 FULL
        OUTER JOIN aws_s3_bucket_cors_rules AS a2 ON a1.selefra_id = a2.aws_s3_buckets_selefra_id
      WHERE
        aws_s3_buckets_selefra_id IS NULL;
    labels:
      tags:
        - Security
        - Misconfigure
      author: Selefra
      standard: Custom
      bucket_url: 'https://{{.name}}.s3.{{.region}}.amazonaws.com'
    metadata:
      id: SF010117
      severity: Low
      provider: AWS
      resource_type: S3
      resource_account_id: '{{.account_id}}'
      resource_id: '{{.name}}'
      resource_region: '{{.region}}'
      remediation: remediation/s3/bucket_is_not_configured_with_cors_rules.md
      title: S3 Bucket is not configured with CORS rules
      description: Ensure to configure secure CORS rules for the Bucket.
    output: 'S3 Bucket is not configured with CORS rules, bucket name: {{.name}}, region: {{.region}}'
